### ISSUE TITLE
LaTeX not working Big Sur 11.3 xournalpp 1.1

### ISSUE THREAD

**Issue by mirkoigel** [xournalpp/xournalpp.github.io#33]
When I try to use "MathTEX" an alert occurs:
"Global template file is not a regular file. Please check your settings."

**Comment by rolandlo** [comment]
What global template file have you set in the LaTeX Panel in menu `Edit > Preferences`?

**Comment by mirkoigel** [comment]
> Am 29.04.2021 um 18:46 schrieb Roland Lötscher ***@***.***>:
> 
> 
> What global template file have you set in the LaTeX Panel in menu Edit > Preferences?
> 
> 
In fact, I didn’t set any. :(

I've copied the „default_template.tex“ from the .app-Folder to my user-home and looked it up using the dialog.
I even corrected the path to pdflatex.

And NOW it’s working!

THANX!

Ps:
But: Why doesn’t xournal find the default template right away?

**Comment by rolandlo** [comment]
According to my knowledge Xournal++ (latest version) should find the default template right away, if it starts with a fresh `settings.xml` file (you can test it out by deleting or renaming that file). Maybe you have changed the default template path previously, so you had some non-default path written into the `settings.xml` file.

**Comment by alvg** [comment]
I had seen this error in snap install.
In the settings file:  snap/xournalpp/current/.config/xournalpp/settings.xml
Replacing
`<property name="latexSettings.globalTemplatePath" value="/snap/xournalpp/61/usr/share/xournalpp/resources/default_template.tex"/>`
to 
`<property name="latexSettings.globalTemplatePath" value="/snap/xournalpp/current/usr/share/xournalpp/resources/default_template.tex"/>`
fixed the problem.
