### ISSUE TITLE
Relicense documentation to creative commons

### ISSUE THREAD

**Issue by Technius** [xournalpp/xournalpp.github.io#42]
We currently have the website code under MIT license, but the MIT license is generally used for code. For the actual writing content, it would probably be better to use a license like CC-BY-4.0. Since the website is at a very early stage, I'm thinking that it would be easier to make this license change now rather than later.

In particular, I propose:
* The existing website code, configuration, and supporting technical files are licensed under MIT.
* Written text files (e.g. markdown files) and images are licensed under some creative commons license.

This license change would require us to get permission from the past contributors.

Thoughts? @rolandlo

**Comment by rolandlo** [comment]
That makes sense to me. I would agree to the license change. CC-BY-4.0 looks like a good choice for the written text files and images. Better now that we have to ask <=5 contributors than later when it gets more complicated.

**Comment by Technius** [comment]
Ok, so let's relicense the written text files to CC-BY-4.0. We only need permission from:

* [ ] @Wisehh 
* [ ] @Mazurel 

Please let us know if you agree or disagree.

**Comment by Mazurel** [comment]
I do agree, it does not seem like a problem for me.

**Comment by Wisehh** [comment]
¡I agree with the relicensing!

**Comment by LittleHuba** [comment]
We require the permission from a few more authors:
@arjun-krishna1
@Fatih20 
@pktiuk

I also agree to relicensing to CC-BY-4.0

**Comment by pktiuk** [comment]
I agree

**Comment by Fatih20** [comment]
> We require the permission from a few more authors:
> 
> * [ ]  @arjun-krishna1
> * [ ]  @Fatih20
> * [x]  @pktiuk
> 
> I also agree to relicensing to CC-BY-4.0

I agree.

**Comment by Technius** [comment]
The only modification that @arjun-krishna1 made is a typo fix, which is probably too minor to be copyrightable in any jurisdiction.

**Comment by LittleHuba** [comment]
Okay then we should go ahead with the relicensing.
