### ISSUE TITLE
Better Home section

### ISSUE THREAD

**Issue by Fatih20** [xournalpp/xournalpp.github.io#45]
I'm interested in making the home section more appealing and more able to sell Xournal++ to new users. It seems that the maintainers, who seems to contribute the most are (rightfully) pre-occupied with engineering the actual software. And so, I'd like to volunteer myself to this. As I also have some ideas such as adding images or an overhaul to how the feature of this software is displayed.

**Comment by rolandlo** [comment]
Great! You're most welcome to contribute. Before you start let me ask you whether you would agree with the (re)licensing of the website contents (written text and images) to `CC-BY-SA-4.0` (instead of `MIT`) as suggested in #42

**Comment by Fatih20** [comment]
> Great! You're most welcome to contribute. Before you start let me ask you whether you would agree with the (re)licensing of the website contents (written text and images) to `CC-BY-SA-4.0` (instead of `MIT`) as suggested in #42

I think CC is better because it's purposefully designed for creative work, unlike MIT which is written for software in mind.

**Comment by Fatih20** [comment]
Tried using `mkdocs serve` to test out local changes but got this error.
`INFO    -  Building documentation... 
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    load_entry_point('mkdocs==0.16.3', 'console_scripts', 'mkdocs')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/__main__.py", line 127, in serve_command
    livereload=livereload
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 110, in serve
    config = builder()
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 101, in builder
    theme_dir=theme_dir
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 181, in load_config
    errors, warnings = cfg.validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 97, in validate
    run_failed, run_warnings = self._validate()
  File "/usr/lib/python3/dist-packages/mkdocs/config/base.py", line 52, in _validate
    self[key] = config_option.validate(value)
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 96, in validate
    return self.run_validation(value)
  File "/usr/lib/python3/dist-packages/mkdocs/config/config_options.py", line 326, in run_validation
    if value in themes:
TypeError: unhashable type: 'dict'`

**Comment by rolandlo** [comment]
Do you also get an error with `mkdocs build`?

**Comment by Fatih20** [comment]
> Do you also get an error with `mkdocs build`?
The exact same error, yes.

**Comment by rolandlo** [comment]
Have you installed the required modules listed in [requirements.txt](https://github.com/xournalpp/xournalpp.github.io/blob/site/requirements.txt)

```pip3 install -r requirements.txt```

**Comment by Fatih20** [comment]
> Have you installed the required modules listed in [requirements.txt](https://github.com/xournalpp/xournalpp.github.io/blob/site/requirements.txt) ?
> 
> `pip3 install -r requirements.txt`

After doing that, I still get the same error.

**Comment by rolandlo** [comment]
What if you `git clone` to a fresh directory and run `mkdocs serve`?
What is your python version, b.t.w.?

**Comment by Fatih20** [comment]
> What if you `git clone` to a fresh directory and run `mkdocs serve`?
> What is your python version, b.t.w.?

I have python 3 and python 2 installed. I've done that and still run to the same issue.

**Comment by LittleHuba** [comment]
Please check your version of mkdocs. From what I found, this happens with some older mkdocs versions and unusual environments.

**Comment by rolandlo** [comment]
I still don't really know why you get an error, but you could try upgrading `mkdocs`:

```
pip3 install --upgrade mkdocs
```
and `mkdocs --version` to see what is installed. I have version 1.2.2

**Comment by Fatih20** [comment]
> I still don't really know why you get an error, but you could try upgrading `mkdocs`:
> 
> ```
> pip3 install --upgrade mkdocs
> ```
> 
> and `mkdocs --version` to see what is installed. I have version 1.2.2

Mine is apparently 0.16.3.

**Comment by rolandlo** [comment]
In case you don't have `pip3`:
```
sudo apt install python3-pip
```

**Comment by Fatih20** [comment]
> In case you don't have `pip3`:
> 
> ```
> sudo apt install python3-pip
> ```

No, I have pip3, I was able to install mkdocs and the other packages with pip3. But I can't run the `mkdocs` command for some reason.

**Comment by LittleHuba** [comment]
Please do never use apt to install python packages. The APT repository is quite often outdated. Use pip instead.

You are most likely running with a different python version as default, for which mkdocs was not installed.

**Comment by LittleHuba** [comment]
You should use a Python virtual environment (venv). That makes your installation clean and straight-forward.

**Comment by rolandlo** [comment]
I can also run `mkdocs` via 
```
python3 ~/.local/bin/mkdocs
```

**Comment by Fatih20** [comment]
> You should use a Python virtual environment (venv). That makes your installation clean and straight-forward.

Alright. I'm now able to run `mkdocs serve`. But my changes doesn't seem to be registered in the locally hosted site that was generated after running `mkdocs serve`.

**Comment by Fatih20** [comment]
> > You should use a Python virtual environment (venv). That makes your installation clean and straight-forward.
> 
> Alright. I'm now able to run `mkdocs serve`. I'll get to work then.

**Comment by Fatih20** [comment]
I take it I'm at liberty to add new css files and modify existing one?

**Comment by rolandlo** [comment]
I think nobody would strictly oppose against that, so just try it out.

**Comment by Fatih20** [comment]
![Better Home Mockup](https://user-images.githubusercontent.com/51940383/127579677-222c962f-ecc1-493c-8500-9ada469aa9f5.png)

This is my suggestion of a simple reordering and removal of redundant information. If we were to do this in conjunction with #47, it'd look like this.

![Better Home Mockup 2](https://user-images.githubusercontent.com/51940383/127580836-8a272660-97b5-464a-9f03-6a4617c044c1.png)


Ideally all of the text are `text-align: center`.

**Comment by Fatih20** [comment]
I have more ideas for the features section below it, but one step at a time.

**Comment by Fatih20** [comment]
@LittleHuba @rolandlo Any inputs to my suggestion? You don't have to work in realizing this concept, I'll do it myself in a PR if approved.

**Comment by LittleHuba** [comment]
I think the download buttons are taking too much space now. I'd prefer some content like pictures or the major features. That is what should convince the user to download Xournal++.

**Comment by Technius** [comment]
I think pictures of Xournal++ are the highest priority in terms of home page improvements. As a new user, I would completely avoid downloading any GUI program if I cannot see any screenshots of it.

Fortunately, @rolandlo has uploaded some awesome demonstration images that we can easily add to a gallery page or to the home page.

As for the proposed download buttons, there is absolutely no indication to the user that those OS images are actually download buttons. They would need to be modified to look more button-like. Also, there are potential copyright issues with using such images.

**Comment by Fatih20** [comment]
> Fortunately, @rolandlo has uploaded some awesome demonstration images that we can easily add to a gallery page or to the home page.

Where can I see this demonstration?

**Comment by Fatih20** [comment]
Following this plan, wouldn't the buttons linking to places need to be put after the features section?

**Comment by Fatih20** [comment]
I made a mock-up of what I think the overall home section should be like taking into account you guys's opinion.
![Better Home 3](https://user-images.githubusercontent.com/51940383/127727330-1b884e23-8038-4213-a8fb-e0e235c252c1.png)

**Comment by rolandlo** [comment]
@Fatih20 Generally speaking I like your mockup of the home section. That's how as a user I would like to get a quick overview what Xournal++ is and what it can do. From the actually listed features I miss the LaTeX tool and export functions.

**Comment by rolandlo** [comment]
> > Fortunately, @rolandlo has uploaded some awesome demonstration images that we can easily add to a gallery page or to the home page.
> 
> Where can I see this demonstration?

See in the `xournalpp-examples` repository https://github.com/xournalpp/xournalpp-examples/tree/main/appdata/screenshots

**Comment by Fatih20** [comment]
> @Fatih20 Generally speaking I like your mockup of the home section. That's how as a user I would like to get a quick overview what Xournal++ is and what it can do. From the actually listed features I miss the LaTeX tool and export functions.

Of course, that can be added in the actual implementation.

**Comment by Fatih20** [comment]
> I made a mock-up of what I think the overall home section should be like taking into account you guys's opinion and mine.
> ![Better Home 3](https://user-images.githubusercontent.com/51940383/127727330-1b884e23-8038-4213-a8fb-e0e235c252c1.png)
> 
> Now obviously this would require a lot of writing CSS and media queries to make it still visible for smartphones. But I'm willing to do that.
> 
> Do let me know of your opinion on this.

Also notice the use of notable and noteworthy in the site of a note-taking software.

**Comment by Fatih20** [comment]
Alright so I'm trying to implement the mockup just to see if it's actually possible. It seems that mkdocs has built-in margin or something because there are margins when they aren't specified in the CSS.

`index.md` :
`<div class = "Xournal" id = "#Xournal" >
	<h1>Xournal++</h1>
	<p>Xournal++ is a <span class = "bold">cross-platform</span>, <span class = "bold">open source</span>, <span class = "bold">hand-written note-taking</span> software with the target of flexibility, functionality, and speed. It is a modern rewrite and more feature-rich version of the wonderful Xournal program.</p>
</div>

<div class = "features" id = "#features">
    <h1>Features</h1>
    <p>Among all of them that are listed in the User Guide, the most notable and noteworthy are...</p>
    <div class = "feature-list">
    	<div class = "feature">
    		<div class = "feature-text">
    			<h2 class = "feature-title">Hand-write your notes</h2>
    			<ul class = "feature-description">
    			    <li>Support for pressure-sensitive stylus and drawing tablets (Wacom, Huion, XP-Pen, etc.)</li>
    			    <li>Robust pen, highlighters, and eraser tool with a lot of customizability, allowing you to write how you want to write</li>
    			</ul>
    		</div>
    		<img class = "feature-image" src = "img/placeholder-image.png">
    	</div>
    </div>
</div>`

`home.css` (I've added this CSS file to the `mkdocs.yml`) :
`* {
	border: solid 1px black;
}

.Xournal, .features{
	text-align: center;
}

.Xournal h1 {
	font-size: 40px;
}

.Xournal p {
}

.bold {
	font-weight: bold;
}

.features h1 {
	font-size: 36px;
}

/*.features {
	border: solid 1px black;
}

.features p{
	border: solid 1px black;
}

.features h1 {
	border: solid 1px black;
}*/

.feature {
	text-align: left;
}

.feature-text, .feature-image {
	display: inline-block;
}

.feature-text {
	/*border: solid 1px black;*/
	width: 40%;
}

.feature h2{
	/*border: solid 1px black;*/
}

.feature ul {
	/*border: solid 1px black;*/
}`


This is how it looks (I purposefully added border to everything to illustrate the issue) :
![image](https://user-images.githubusercontent.com/51940383/127739461-b7c37efe-f6fa-47be-8b9c-75bec37d9b99.png)

As you see, between Xournal++ title and its description, there is a margin when it's not specified in the CSS. Same goes for the `h1` and `p` in the `features` class. More importantly, the `feature-title` is not vertically-align with the `feature-text` `div` which makes it look strange. If `feature-title` is changed to `h1` from `h2`, it would be vertically-align with the `feature-text` `div`.

**Comment by Fatih20** [comment]
> I made a mock-up of what I think the overall home section should be like taking into account you guys's opinion and mine.
> ![Better Home 3](https://user-images.githubusercontent.com/51940383/127727330-1b884e23-8038-4213-a8fb-e0e235c252c1.png)
> 
> Now obviously this would require a lot of writing CSS and media queries to make it still visible for smartphones. But I'm willing to do that.
> 
> Do let me know of your opinion on this.

![Better Home 4](https://user-images.githubusercontent.com/51940383/127767724-1e89f49a-5be8-4dc0-ba38-3f929e8f97f7.png)

I've refined the idea and improved the mock-up to this because the images in previous idea is too small. Added bonus of this new mock-up is that the media queries that would need to be written is fewer because the overall layout in smartphone would be similar.

**Comment by Fatih20** [comment]
On a separate note, is there a way to increase the `max-width` for the whole site? As seen from the mockup and from the screenshot of the site as is right now, there's a whole lot of space that should've been used. I'm using a 1440p monitor for viewing the site.

![Bad Use of Space](https://user-images.githubusercontent.com/51940383/127767945-df891a32-1bf3-458d-85d3-7e0c1761c7d5.png)

**Comment by rolandlo** [comment]
> On a separate note, is there a way to increase the `max-width` for the whole site? As seen from the mockup and from the screenshot of the site as is right now, there's a whole lot of space that should've been used. I'm using a 1440p monitor for viewing the site.
> 
Does https://github.com/squidfunk/mkdocs-material/issues/619 help?

**Comment by Fatih20** [comment]
> Alright so I'm trying to implement the mockup just to see if it's actually possible. It seems that mkdocs has built-in margin or something because there are margins when they aren't specified in the CSS.
> 
> `index.md` :
> 
> ```
> <div class = "Xournal" id = "#Xournal" >
> 	<h1>Xournal++</h1>
> 	<p>Xournal++ is a <span class = "bold">cross-platform</span>, <span class = "bold">open source</span>, <span class = "bold">hand-written note-taking</span> software with the target of flexibility, functionality, and speed. It is a modern rewrite and more feature-rich version of the wonderful Xournal program.</p>
> </div>
> 
> <div class = "features" id = "#features">
>     <h1>Features</h1>
>     <p>Among all of them that are listed in the User Guide, the most notable and noteworthy are...</p>
>     <div class = "feature-list">
>     	<div class = "feature">
>     		<div class = "feature-text">
>     			<h2 class = "feature-title">Hand-write your notes</h2>
>     			<ul class = "feature-description">
>     			    <li>Support for pressure-sensitive stylus and drawing tablets (Wacom, Huion, XP-Pen, etc.)</li>
>     			    <li>Robust pen, highlighters, and eraser tool with a lot of customizability, allowing you to write how you want to write</li>
>     			</ul>
>     		</div>
>     		<img class = "feature-image" src = "img/placeholder-image.png">
>     	</div>
>     </div>
> </div>
> ```
> 
> `home.css` (I've added this CSS file to the `mkdocs.yml`) :
> 
> ```
> * {
> 	border: solid 1px black;
> }
> 
> .Xournal, .features{
> 	text-align: center;
> }
> 
> .Xournal h1 {
> 	font-size: 40px;
> }
> 
> .Xournal p {
> }
> 
> .bold {
> 	font-weight: bold;
> }
> 
> .features h1 {
> 	font-size: 36px;
> }
> 
> /*.features {
> 	border: solid 1px black;
> }
> 
> .features p{
> 	border: solid 1px black;
> }
> 
> .features h1 {
> 	border: solid 1px black;
> }*/
> 
> .feature {
> 	text-align: left;
> }
> 
> .feature-text, .feature-image {
> 	display: inline-block;
> }
> 
> .feature-text {
> 	/*border: solid 1px black;*/
> 	width: 40%;
> }
> 
> .feature h2{
> 	/*border: solid 1px black;*/
> }
> 
> .feature ul {
> 	/*border: solid 1px black;*/
> }
> ```
> 
> This is how it looks (I purposefully added border to everything to illustrate the issue) :
> ![image](https://user-images.githubusercontent.com/51940383/127739461-b7c37efe-f6fa-47be-8b9c-75bec37d9b99.png)
> 
> As you see, between Xournal++ title and its description, there is a margin when it's not specified in the CSS. Same goes for the `h1` and `p` in the `features` class. More importantly, the `feature-title` is not vertically-aligned with the `feature-text` `div` which makes it look strange. However, if `feature-title` is changed to `h1` from `h2`, it would be vertically-aligned with the `feature-text` `div`.

Regarding this, I've asked directly to mkdocs and it's solved.
https://github.com/squidfunk/mkdocs-material/discussions/2890

**Comment by Fatih20** [comment]
> > On a separate note, is there a way to increase the `max-width` for the whole site? As seen from the mockup and from the screenshot of the site as is right now, there's a whole lot of space that should've been used. I'm using a 1440p monitor for viewing the site.
> 
> Does [squidfunk/mkdocs-material#619](https://github.com/squidfunk/mkdocs-material/issues/619) help?

I'll look into it and try it out.

**Comment by Fatih20** [comment]
Alright, I've managed to actually create the site in accordance to the mock-up.
![image](https://user-images.githubusercontent.com/51940383/127798169-670e46fd-0c4a-479d-bde4-7148ad762b43.png)

`index.md` :
```
<div class = " home Xournal" id = "#Xournal" >
	<h1>Xournal++</h1>
	<p>Xournal++ is a <span class = "bold">cross-platform</span>, <span class = "bold">open source</span>, <span class = "bold">hand-written note-taking</span> software with the target of flexibility, functionality, and speed. It is a modern rewrite and more feature-rich version of the wonderful Xournal program.</p>
</div>

<div class = "home features" id = "#features">
    <h1>Features</h1>
    <p>Among all of them that are listed in the User Guide, the most notable and noteworthy are...</p>
    <div class = "home feature-list">
    	<div class = "home feature">
    	    <div class = "home feature-container">
    	        <div class = "home feature-text">
    	            <h2 class = "feature-title">Hand-write your notes</h2>
    	            <p>Support for pressure-sensitive stylus and drawing tablets (Wacom,
Huion, XP-Pen, etc.)</p>
    	            <p>Robust pen, highlighters, and eraser tool with a lot of customizability,
allowing you to <span class = "bold">write how you want to write</span></p>
    	        </div>
    	        <img class = "feature-image" src = "img/placeholder-image-2.png">
    	    </div>
    	</div>
    </div>
</div>
```

`home.css` (I've added this to `mkdocs.yml`:
```
.home h1, .home h2, .home p, .home ul, .home li {
	margin: 0;
	padding: 0;
	/*border: solid 1px black;*/
}

.bold {
	font-weight: bold;
}

.Xournal, .features{
	text-align: center;
}

.Xournal h1 {
	font-size: 40px;
	margin-bottom: 10px;
}

.Xournal {
	margin-bottom: 40px;
}

.features h1 {
	font-size: 36px;
}

.feature {
	margin: 0 auto;
	margin-top: 40px;
	/*border: solid 1px black;*/
}

.feature-image, .feature-text{
	display: block;
}

.feature-text {
	text-align: left;
	margin-bottom: 30px;
	/*border: solid 1px black;*/
}

.feature h2 {
	margin-bottom: 15px;
}
```

Now I just need to look into making the content fills the whole screen. Another thing I got from this, is that there should be a screenshot of the application right below Xournal++ description before features.

**Comment by Fatih20** [comment]
> > On a separate note, is there a way to increase the `max-width` for the whole site? As seen from the mockup and from the screenshot of the site as is right now, there's a whole lot of space that should've been used. I'm using a 1440p monitor for viewing the site.
> 
> Does [squidfunk/mkdocs-material#619](https://github.com/squidfunk/mkdocs-material/issues/619) help?

I just tried out setting max-width to 90% in this code snippets. I think I'll have to go back to the drawing board and increase the font-size across the board if we're going through with this.
![image](https://user-images.githubusercontent.com/51940383/127798940-8ce8036b-b56a-407a-9d7d-0bf92c17d140.png)

**Comment by Fatih20** [comment]
>  Another thing I got from this, is that there should be a screenshot of the application right below Xournal++ description before features.

I think this screenshot (https://github.com/xournalpp/xournalpp-examples/blob/main/appdata/screenshots/note_taking_1600x900.png) is a good candidate for this. However, the color here are too saturated and unappealing. Assuming that you have the raw file, can you send the raw file over to me so I could change the colors and take the screenshot at a larger size? @rolandlo

**Comment by rolandlo** [comment]
@Fatih20 The raw files are in the same repository, just one level up: https://github.com/xournalpp/xournalpp-examples/tree/main/appdata

**Comment by Fatih20** [comment]
> However, removing margins for `h1` and `h2` without exception would break other sections of the site which is designed with this built-in margin in mind. Is there a way to apply a css specifically for only one page?

I've asked them again and solve the problem. https://github.com/squidfunk/mkdocs-material/discussions/2893

**Comment by rolandlo** [comment]
> I recreated the sample note to make it look like an actual hand-written note (seems like the original file was created with a mouse).

That's not true! I've created the original file using my Wacom tablet and tried to write as nicely as possible. There is varying pressure, which you can see from the .xopp file contents. The colors may be better now, but I really don't think the handwriting is any better.

**Comment by Fatih20** [comment]
> > I recreated the sample note to make it look like an actual hand-written note (seems like the original file was created with a mouse).
> 
> That's not true! I've created the original file using my Wacom tablet and tried to write as nicely as possible. There is varying pressure, which you can see from the .xopp file contents. The colors may be better now, but I really don't think the handwriting is any better.

Maybe the Wacom tablet has lower report rate than my drawing tablet. The previous writing is a bit jaggy.

**Comment by Fatih20** [comment]
> > Maybe your Wacom tablet has a lower report rate than my drawing tablet. The previous writing is a bit jaggy.
> 
> Fair point, but currently it goes at the expense of other things like horizontal placement, length of underline marks, the "=" signs etc.
> In particular I don't like the underline mark below "Exercise from", the "=" signs, the horizontal placement of "theta" on the right of the picture, of the multiplication dot after the first "=" sign, of the `sin` and of the fraction below that. Just compare with the original.
> The current new version looks too sloppy for my taste.

Alright I could fix all of those issues. But isn't that an organic look on how most people uses this software?

**Comment by rolandlo** [comment]
In my opinion there is a justified difference between what is an organic look and what you would like to present to thousands of people.

**Comment by Fatih20** [comment]
![Screenshot from 2021-08-02 16 51 04](https://user-images.githubusercontent.com/51940383/127842393-66415a55-a722-42c5-a5e3-04351af37d95.png)

How about this? I've tidied it up and rewrote all of it.

**Comment by rolandlo** [comment]
Still the vertical placement is an issue (sorry that I wrote "horizontal" instead of "vertical" before). The multiplication dots and the fraction line should be vertically aligned to the middle of a lowercase letter like m or v, as your LaTeX editor would do it as well:

![grafik](https://user-images.githubusercontent.com/40485433/127843627-5455b667-d34f-4f9a-b60b-5788afc33f13.png)

Moreover I would only underline "Exercise", since "from" is less important.

Also I have noticed that you removed the link to the license for the image. This might be a problem. Please check the license text.

**Comment by Fatih20** [comment]
> Also I have noticed that you removed the link to the license for the image. This might be a problem. Please check the license text.

Is the license for the picture of the problem being worked on in the file or is the license for the screenshot itself?

**Comment by rolandlo** [comment]
It's the license for the picture of the problem.

**Comment by Fatih20** [comment]
![Screenshot from 2021-08-02 17 21 29](https://user-images.githubusercontent.com/51940383/127846640-db67861d-9df7-40ea-b030-33e1da1a8fa1.png)

Here's further revision.

**Comment by rolandlo** [comment]
> Here's further revision.

That looks much better. The fraction line is not fixed yet 
![grafik](https://user-images.githubusercontent.com/40485433/127847471-7182cc61-fff6-4e27-8955-6dbb1d992a5f.png)
Please compare with the original version.

**Comment by Fatih20** [comment]
![Screenshot from 2021-08-02 17 34 10](https://user-images.githubusercontent.com/51940383/127848308-2c537f46-dbc6-4cb7-a632-5e7a9cf12947.png)

Fixed the line and tidied up the fraction.

**Comment by rolandlo** [comment]
The fraction line is still below the multiplication dot. That looks wrong. They should be exactly on the same height. Also I just noticed that you put brackets around the 0.15 unnecessarily. Please remove them.

**Comment by Fatih20** [comment]
![Screenshot from 2021-08-02 17 43 23](https://user-images.githubusercontent.com/51940383/127849581-70d3ffb3-019d-4d13-abd2-bbf40b9d2cfa.png)

Fixed those issues.

> The fraction line is still below the multiplication dot. That looks wrong. They should be exactly on the same height. Also I just noticed that you put brackets around the 0.15 unnecessarily. Please remove them.

**Comment by rolandlo** [comment]
I think it is fine now.

**Comment by Fatih20** [comment]
Ok great.

> I think it is fine now.

**Comment by Technius** [comment]
Looks good to me, go ahead and submit a PR.

**Comment by Fatih20** [comment]
> Looks good to me, go ahead and submit a PR.

Oh no no. The most recent mock-up isn't final at all. As I've said, I'm going back to the drawing board.

**Comment by Fatih20** [comment]
Is there a way to change the color of the header? The purple-ish ultramarine is not respresentative of Xournal++ at all and is going to clash with what I'm going for. A plain old black would be better.

**Comment by Fatih20** [comment]
I'm planning to use Montserrat as the font for the home section. Since it's licensed under OFL, I believe it's completely legal.

**Comment by Fatih20** [comment]
![Better Home 5](https://user-images.githubusercontent.com/51940383/127940330-590a5f86-e3e4-4cfc-8813-bc4d6491c661.png)

Alright, this is the general structure of what the site is going to look like, but the layout, margins, and sizes of everything isn't final. And you're also welcome to give input on how every notable features are represented here.

What I'm lobbying right now is for the removal of table of content, and I'll walk you through the reasoning step by step.

Because of the structure of the site according to this mock-up, the "headline" so to speak is available right there, and the list of features is just one little scroll away so I think it's reasonable say that both doesn't need to be included in the table of content.

Now, you might argue that there is plenty of feature being showcased in the home section, so that would be a great addition to the table of contents. That's a bad idea because of 3 reasons :

- The table of content would look like a list of empty marketing jargons that isn't immediately backed up with anything. Which is a bad first impression for anybody that is just discovering this app.
- New visitors may get overwhelmed knowing the amount of information they are expected to receive just by visiting. If the content isn't included in the table of content, they would be more enticed to scroll down and see all of the features since they don't know how long the information is.
- It spoils the visitor from the cathartic of discovering the features of this software. Their awe and sense of wonder would've been higher if they had scrolled down without knowing what to expect.

That's considering the content, now from the perspective of layout.

As you can see in the mock-up above, the table of content creates plenty of unused space from top to bottom. Any table of content in the home section should be better integrated to the section and not look like a rushed patch. As I've mentioned how the headline, list of feature, and the individual of features shouldn't be included, that leaves the download section. It's easy for me to make a "Download Now!" button near the top before the feature list that links you to the download section at the bottom of the home page.

@rolandlo @Technius @LittleHuba

**Comment by Fatih20** [comment]
I'm currently going to make a mock-up with a fixed `max-width` since it's now obvious setting it to a 90% is a bad idea because the picture would overwhelm and dominate over the text in big monitor.

**Comment by Fatih20** [comment]
> ![Better Home 5](https://user-images.githubusercontent.com/51940383/127940330-590a5f86-e3e4-4cfc-8813-bc4d6491c661.png)
> 
> Alright, this is the general structure of what the site is going to look like, but the layout, margins, and sizes of everything isn't final. And you're also welcome to give input on how every notable features are represented here.
> 
> What I'm lobbying right now is for the removal of table of content, and I'll walk you through the reasoning step by step.
> 
> Because of the structure of the site according to this mock-up, the "headline" so to speak is available right there, and the list of features is just one little scroll away so I think it's reasonable say that both doesn't need to be included in the table of content.
> 
> Now, you might argue that there is plenty of feature being showcased in the home section, so that would be a great addition to the table of contents. That's a bad idea because of 3 reasons :
> 
> * The table of content would look like a list of empty marketing jargons that isn't immediately backed up with anything. Which is a bad first impression for anybody that is just discovering this app.
> * New visitors may get overwhelmed knowing the amount of information they are expected to receive just by visiting. If the content isn't included in the table of content, they would be more enticed to scroll down and see all of the features since they don't know how long the information is.
> * It spoils the visitor from the cathartic of discovering the features of this software. Their awe and sense of wonder would've been higher if they had scrolled down without knowing what to expect.
> 
> That's considering the content, now from the perspective of layout.
> 
> As you can see in the mock-up above, the table of content creates plenty of unused space from top to bottom. Any table of content in the home section should be better integrated to the section and not look like a rushed patch. Since I've mentioned how the headline, list of feature, and the individual features shouldn't be included, that leaves the download section. It's easy for me to make a "Download Now!" button near the top before the feature list that links you to the download section at the bottom of the home page.
> 
> @rolandlo @Technius @LittleHuba

And yes, I would add a reference to the Guide section for a complete list of features.

**Comment by LittleHuba** [comment]
I agree. No table of contents.

**Comment by rolandlo** [comment]
> I agree. No table of contents.

I second that.

**Comment by Fatih20** [comment]
> Is there a way to change the color of the header? The purple-ish ultramarine is not representative of Xournal++ at all and is going to clash with what I'm going for. A plain old black would be better.

Solved. I just changed the `scheme` in `mkdocs.yml` from `indigo` to `black`.

**Comment by Technius** [comment]
The top two reasons why users would want to visit the home page are:
1. They are new to the software
2. They are trying to download Xournal++

The proposed changes here address the first reason well, but I feel like they don't address the second one adequately.

I agree in that we should drop the TOC. Hypothetically, if we were to include a TOC, it would only include the Features and Download links. This would be entirely pointless since there are only two items.

> It's easy for me to make a "Download Now!" button near the top before the feature list that links you to the download section at the bottom of the home page.

Alternatively, why not move the download button to the top of the page? The download area does not take much space, so this does not deter users visiting with reason 1. Secondly, having the download buttons at the top of the page helps users with reason 2. There's a reason why so many software put the download page at the very top (examples: [LibreOffice](https://www.libreoffice.org/), [Firefox](https://www.mozilla.org/en-US/firefox/new/), [GIMP](https://www.gimp.org/), [IINA](https://iina.io/), etc.).

---

Here are some of my thoughts on the new layout:

* I like the color change.
* The very first "feature" is an introduction section; hence, it should include the string "Xournal++" somewhere!
* This layout is suitable for mobile users but terrible for desktop users. The the side-by-side layout from the first mockup (with some modifications) is superior for desktop users, in my opinion. The except is the first summary "feature", which should prominently display a full example of Xournal++.
*

**Comment by Fatih20** [comment]
> Alternatively, why not move the download button to the top of the page? The download area does not take much space, so this does not deter users visiting with reason 1. Secondly, having the download buttons at the top of the page helps users with reason 2. There's a reason why so many software put the download page at the very top (examples: [LibreOffice](https://www.libreoffice.org/), [Firefox](https://www.mozilla.org/en-US/firefox/new/), [GIMP](https://www.gimp.org/), [IINA](https://iina.io/), etc.).

The reason I put the downloads at the bottom is because one the first thing said to me is that the first things new visitors see shouldn't be the download button, but rather, reasons why they should download Xournal++. Ideally, the 'installation' in the heading should transport you to the download section at the home. But I have doubts on whether that's possible.

> * The very first "feature" is an introduction section; hence, it should include the string "Xournal++" somewhere!

The reason I didn't include Xournal++ is that the logo and name of the software is already displayed in the top left corner of the heading. Adding 'Xournal++' in the title felt redundant. But alright, I'll put Xournal++ there somewhere.

> * This layout is suitable for mobile users but terrible for desktop users. The the side-by-side layout from the first mockup (with some modifications) is superior for desktop users, in my opinion. The exception is the first summary "feature", which should prominently display a full example of Xournal++.

Do you think so because scrolling through the entire page is easier with that layout?

**Comment by Fatih20** [comment]
https://user-images.githubusercontent.com/51940383/128096332-f19e0343-14a2-40e6-b1d3-036b9f0e88df.mp4

It's working. But @Technius is correct, this is quite a pain in the desktop. It was barely okay with 1440p monitor but it's just uncomfortable with 1080p monitor because the title and the picture doesn't fit the screen.

**Comment by Technius** [comment]
> I'll go back to the drawing board.

We can add some CSS media rules that automatically switch the layout to side-by-side (or a better layout) if the screen width is greater than some bound (e.g. `>= 1200px`). I think the two proposed layouts work well for us here, as long as we design the mobile layout for mobile (or vertical tablet) and the desktop layout for desktop (or horizontal tablet).

**Comment by Fatih20** [comment]
> > I'll go back to the drawing board.
> 
> We can add some CSS media rules that automatically switch the layout to side-by-side (or a better layout) if the screen width is greater than some bound (e.g. `>= 1200px`). I think the two proposed layouts work well for us here, as long as we design the mobile layout for mobile (or vertical tablet) and the desktop layout for desktop (or horizontal tablet).

https://user-images.githubusercontent.com/51940383/128115861-a8d51d7b-f3d8-4a6a-99d6-cebf08e81a12.mp4


I may have used too many media queries. I'll go make a pull request since it's mostly done now.

**Comment by Fatih20** [comment]
The PR is merged, so this issue will be closed.
