### ISSUE TITLE
Streamlining the installation page.

### ISSUE THREAD

**Issue by Fatih20** [xournalpp/xournalpp.github.io#47]
![image](https://user-images.githubusercontent.com/51940383/127577527-48c064a9-0156-460c-9cee-c821dfb07970.png)
If the installation page consist only of 3 short paragraph and 3 buttons, isn't it better to streamline it by putting these in the home section instead?

**Comment by Fatih20** [comment]
You could put replace the line directing visitor to the installation page with the actual page.
![image](https://user-images.githubusercontent.com/51940383/127577745-cd4725d0-fb2d-4bbd-bd95-474aed3bcc39.png)

It would reduce the amount of click needed for users to start installing this software.

**Comment by Technius** [comment]
> If the installation page consist only of 3 short paragraph and 3 buttons, isn't it better to streamline it by putting these in the home section instead?

Someone who clicks the "Installation" link at the top will need to be shown this page, otherwise they will become confused.

> You could put replace the line directing visitor to the installation page with the actual page.

I agree. More concretely, I think it would be better to replace "Download" with "Download for Linux", "Download for Mac", and "Download for Windows" buttons.

**Comment by Fatih20** [comment]
> > If the installation page consist only of 3 short paragraph and 3 buttons, isn't it better to streamline it by putting these in the home section instead?
> 
> Someone who clicks the "Installation" link at the top will need to be shown this page, otherwise they will become confused.
> 

Instead of redirecting to a new page, what if clicking the installation link just speed scroll you to the part in the homepage with the install button? Set the div container for the download button as `id = downloads` and then make the installation button `href = #downloads`. Granted, the installation button is autogenerated by mkdocs or whatever and not an actual `a` object. But is this possible?
