### ISSUE TITLE
Are the table of contents necessary in the home section?

### ISSUE THREAD

**Issue by Fatih20** [xournalpp/xournalpp.github.io#48]
![image](https://user-images.githubusercontent.com/51940383/127577880-913490b0-d4d4-4896-be34-ca7e2de87e6c.png)

The table of content doesn't seem to be very useful as of right now considering that there's not that many content to justify its existence. But even if there were many contents, you don't see table of content in the home section of most software, because it makes what is supposed to be one's first impression of the software less elegant, feeling more like a documentation page. 

Moreover, should there be quite many content in this page, potential new users could see how long the table of content is, and get intimidated.

**Comment by Technius** [comment]
The table of contents is autogenerated for each page and provides useful navigation options, e.g.:
![image](https://user-images.githubusercontent.com/1066652/127601681-3fe57782-efee-4cde-9c46-ae330de06f99.png)

**Comment by Fatih20** [comment]
I'm aware of its use in certain pages. But in home section? If it's impossible to not generate it for certain pages, then sure.

**Comment by Technius** [comment]
Ok, it seems like it is possible to hide it on the home page ([see this](https://github.com/mkdocs/mkdocs/issues/700#issuecomment-126749442)). Personally, I would find the TOC useful for jumping to sections on the home page that I care about (e.g. killer features, screenshots, download links, etc.).

**Comment by Fatih20** [comment]
Alright, I still stand by my opinion.
