### ISSUE TITLE
Link dead on guide on website

### ISSUE THREAD

**Issue by new-on-github** [xournalpp/xournalpp.github.io#83]
The Link
https://xournalpp.github.io/guide/resources/xopp-to-pdf
to the script on this page of the guide
https://xournalpp.github.io/guide/tips/
is dead.

Hopefully this is the right location for a mistake in the guide.

Thanks a lot!

**Comment by Technius** [comment]
Thanks for finding this issue, there's a typo in the link.

You can find the script here: https://github.com/xournalpp/xournalpp.github.io/blob/site/docs/resources/xopp-to-pdf
