### ISSUE TITLE
Can't type text in text fields

### ISSUE THREAD

**Issue by Masacroso** [xournalpp/xournalpp.github.io#90]
I'm using up to date manjaro rolling release and installed xournal++. But I can't write type text in any text field. Its like my typing is not registered, just a blinking cursor stay in the field text but no type is registered.

**Comment by rolandlo** [comment]
This is the issue tracker of the website, not of the app itself. Most likely your issue can be solved as in https://github.com/xournalpp/xournalpp/issues/4572
